### ISSUE TITLE
Plans to publish on PyPi

### ISSUE THREAD

**Issue by iamrecursion** [amakelov/mandala#29]
Do you have any plans to publish Mandala on the python package index? I've got a couple of environments that can't install from git, but can pull from PyPi so it would definitely be useful for me!

**Comment by amakelov** [comment]
Thanks for the suggestion! I'll look into it

**Comment by iamrecursion** [comment]
Awesome, thank you!

**Comment by amakelov** [comment]
Hi, sorry for the delay - this is ongoing, I'm trying get ownership of the `mandala` project on PyPi to avoid having to change the name.

**Comment by iamrecursion** [comment]
No worries at all! Thanks for the update! You could always go with `mandala-engine` or something if that proves impossible.

**Comment by amakelov** [comment]
The project is now on PyPi under the name `pymandala`: https://pypi.org/project/pymandala/0.2.0a0/ ! 

You should be able to install the current PyPi version via `pip install pymandala`. 

The project should still be imported as `import mandala`, etc. Let me know if there are any issues!

**Comment by iamrecursion** [comment]
Thank you so much! This works so far!
